config/routes.rb
Bd::Application.routes.draw do
  root :to => 'home#new'
  get 'story' => 'home#story'
  get 'schedule' => 'home#schedule'
  get 'events' => 'home#events'
  get 'contact' => 'home#contact'
  get 'pickup' => 'order#pickup'
  get 'soldout' => 'order#soldout'
  get 'thankyou' => 'order#thankyou'
  get 'closed' => 'order#closed'
  get 'phone' => 'twilio#phone'
  get 'call' => 'twilio#call'
  get 'twilio-directions' => 'twilio#twilio-directions'
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def new
    Time.use_zone('GMT') do
      now = Time.zone.now - 14400 # GMT less four hours = NY time
      start_of_day = now.at_midnight
      eightam = start_of_day + 28800 # 8am = 8 * 60 * 60
      onepm = start_of_day + 52200 # 1pm = 13 * 60 * 60
      @e = eightam
      @o = onepm
      @n = now
    end
  end
  def story
  end
  def schedule
  end
  def events
  end
  def contact
  end
end

app/controllers/twilio_controller.rb
class TwilioController < ApplicationController

  def phone
    Time.use_zone('GMT') do
      now = Time.zone.now - 14400 # GMT less four hours = NY time
      start_of_day = now.at_midnight
      eightam = start_of_day + 28800 # 8am = 8 * 60 * 60
      onepm = start_of_day + 46800 # 1pm = 13 * 60 * 60
      @e = eightam
      @o = onepm
      @n = now
    end
    render :action => 'phone.xml.builder', :layout => false
  end
  def call
    @post_to = 'http://www.biandangnyc.com/twilio_directions'
    @response = Twilio::TwiML::Response.new do |r|
      r.Say 'hello there', :voice => 'alice'
      r.Dial :callerId => '+14159992222' do |d|
        d.Client 'jenny'
      end
    end
    render :action => 'call.html.slim', :layout => false
  end
  def twilio_directions
    #test
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def nav_link(link_text, link_path)
    class_name = current_page?(link_path) ? 'active' : ''

    content_tag(:li, :class => class_name, :class => 'nav-li' ) do
      link_to link_text, link_path
    end
  end
  def nav_link_small(link_text, link_path)
    class_name = current_page?(link_path) ? 'active' : ''

    content_tag(:li, :class => class_name, :class => 'nav-li-small' ) do
      link_to link_text, link_path
    end
  end

end

app/views/home/contact.html.slim
.row
  .col-md-8
    .panel.panel-default
      .panel-heading
        h1 By Internet
      .panel-body
        ' You can email
        a href='mailto:ty@luckmgmt.com' ty@luckmgmt.com
        |  or fill the form below:
        iframe src="https://docs.google.com/spreadsheet/embeddedform?formkey=dExja1hoTUdGakx5WjA4endYdUFDR0E6MQ" width="98%" height="770" frameborder="0" marginheight="0" marginwidth="0" Loading...
  .col-md-4
    .panel.panel-default
      .panel-heading
        h1 By Phone
      .panel-body
        h2 +1 (212) 695-5995
        h2 +1 (800) 69-LUCK
        / | Phone Directory:
        / ol
        /   li To Locate a Food Truck
        /   ol
        /     li Bian Dang
        /     li Domo Taco
        /     li Moo Shu Grill
        /   li Operator
        /   li To Leave a Message for the Owners
        /   li For a Joke

app/views/home/events.html.slim
.row
  .col-md-8.col-md-offset-2
    <iframe height="1193" allowTransparency="true" frameborder="0" scrolling="no" style="width:100%;border:none"  src="https://luckmgmt.wufoo.com/embed/m1o9xzpx0kurz5x/"><a href="https://luckmgmt.wufoo.com/forms/m1o9xzpx0kurz5x/">Fill out my Wufoo form!</a></iframe><div id="wuf-adv" style="font-family:inherit;font-size: small;color:#a7a7a7;text-align:center;display:block;"></div>

app/views/home/new.html.slim
.row
  .col-md-6
    .panel.panel-default
      .panel-heading
        h1 Entrees
      .panel-body
          h4.menu-item Fried Chicken over Rice
          h4.price $ 7.00
          .clearfix
          h5.item-desc Taiwanese style fried chicken leg over jasmine rice served with pan-fried pickled mustard greens and doused with our famous minced pork sauce.

          h4.menu-item Fried Pork Chop over Rice
          h4.price $ 7.00
          .clearfix
          h5.item-desc Taiwanese style fried pork chop over jasmine rice served with pan-fried pickled mustard greens and doused with our famous minced pork sauce.

          h4.menu-item Fried Fish Cake (tian-bu-la) over Rice
          h4.price $ 8.00
          .clearfix
          h5.item-desc Taiwanese style fried fish cake over jasmine rice served with pan-fried pickled mustard greens and doused with our famous minced pork sauce.

          h4.menu-item Snack Platter
          h4.price $ 4.00
          .clearfix
          h5.item-desc Tea egg over jasmine rice served with pan-fried pickled mustard greens and doused with our famous minced pork sauce.

          / h4.menu-item Beef Stew over Rice
            h4.price $ 9.00
            .clearfix
            h5.item-desc Slow stewed beef chunks, beef tendons, carrots, celery, onions and potatoes over jasmine rice.

          h4.menu-item Extra Pork Chop or Fried Chicken
          h4.price $ 5.00
          .clearfix
          h5.item-desc An extra piece of our crispy fried Chicken or Pork Chop, mmm-hmmm.
  .col-md-6
    .panel.panel-default
      .panel-heading
        h1 Sides
      .panel-body
        h4.menu-item Steamed Pork Dumplings
        h4.price $ 3.00
        .clearfix
        h5.item-desc Four (4) pieces of delicous pork dumplings. Sauces are self-serve.
        h4.menu-item Steamed Mini Pork Buns
        h4.price $ 3.00
        .clearfix
        h5.item-desc Three (3) pieces of delicious mini pork buns.
        h4.menu-item Zong-zi (Chinese Tamale)
        h4.price $ 4.00
        .clearfix
        h5.item-desc Glutinous rice, pork belly, Chinese sausage, peanuts, dried shrimp, green beans, radish, mushroom and Szechuan vegetables wrapped in bamboo leaves and steamed. PSA: Do not eat bamboo leaves unless you are a panda.
        h4.menu-item Vegetarian Zong-zi
        h4.price $ 4.00
        .clearfix
        h5.item-desc Glutinous rice, peanuts, green beans, radish, mushroom and Szechuan vegetables wrapped in bamboo leaves and steamed. PSA: Do not eat bamboo leaves unless you are a panda.
        h4.menu-item Buddha's Delight
        h4.price $ 3.00
        .clearfix
        / h5.item-desc Tofu, bean curd, bamboo shoots, mushrooms and woodear stir-fried in a special blend of savory sauce, served cold.
          h4.menu-item Dried Anchovies & Peanuts
          h4.price $ 3.00
          .clearfix
        / h5.item-desc Dried anchovies and peanuts, seasoned and stir-fried, served cold.
          h4.menu-item Tea Egg
          h4.price $ 1.00
          .clearfix
        h5.item-desc Hard boiled egg infused with flavors from tea leaves, soy sauce, and secret spices.

app/views/home/schedule.html.slim
.row
  .col-md-7
    .panel.panel-default
      .panel-heading
        h1 Schedule
      .panel-body
        h3 Monday to Friday / 11:30am to 2:30pm
        h4 Midtown East
        p 53rd street between Park and Lexington avenue
        h3 Weekends / Off
        p We are usually off, but please check our Twitter account.
  .col-md-5
    = render '/layouts/twitter'

app/views/home/story.html.slim
.row
  .col-md-12
    .panel.panel-default
      .panel-heading
        h1 Our Story
      .panel-body
        p Where can one get Taiwanese-style fried chicken over rice, seasoned with a delicious home-cooked pork sauce, with tea eggs and handmade dumplings on the side? Earlier this summer, possibly the first Taiwanese-style food truck in the United States drove into town and opened for lunch at neighborhoods around New York City. The response? Long lines and lively word-of-mouth between friends and foodblogs—enough so that NYC Cravings sold out of their signature fried chicken at their first appearance in Midtown.
        p Earlier this summer, possibly the first Taiwanese-style food truck in the United States drove into town and opened for lunch at neighborhoods around New York City. The response? Long lines and lively word-of-mouth between friends and foodblogs—enough so that NYC Cravings sold out of their signature fried chicken at their first appearance in Midtown.
        p Cravings began April 28th with an evolving menu that currently includes entrees of chicken, pork chop, and fish with additional options of tea egg, pork or vegetable dumplings, and various Asian drinks such as Chrysanthemum tea, Aloe Vera, and Grass Jelly.
        p Every weekday, the pale yellow and bamboo-decorated truck parks at a different location from about 11:00 a.m. to 2:00 p.m. Sundays find them in Brooklyn, and Twitter lets them communicate other impromptu appearances (such as a recent stop near Lincoln Center for the city’s first annual Pan-Asian Basketball Tournament where Team Taiwan made it to the championship).
        p The Cravings website lists the general stopping areas for each day, but the truck also makes helpful announcements on exact locations, arrival times, and food changes (including the horrifying likelihood of food favorites running low on busy days) via Twitter. So part of the fun for the growing number of Cravings devotees lies in ‘stalking’ the truck around town due to the unpredictable nature of NYC parking, traffic and other factors.
        p The rapid rise in Cravings’ profile has come from a mix of traditional word-of-mouth, online buzz and media coverage. Though the first few days started out slowly, less than two weeks later, write-ups from notable food blog Midtown Lunch mobbed the truck with customers the next day. “We got swamped,” says Thomas Yang, one of the owners of Cravings. “We ran out of chicken in half an hour.”
        p Word continued to spread, including mention and feature photo in the widely discussed New York Times article on the recent food truck craze. Meanwhile, the Cravings staff worked hard on learning how to serve up to hundreds of people in three hours from within the confines of 20-something square feet of space—in the summer heat, no less.
        p So who is responsible for this four-wheeled enterprise? The creative team behind Cravings consists of Thomas Yang, his sister Diana and their business partner Eric.
        p Yang grew up in the New York area and graduated from Baruch College and says that the initial idea for Cravings “started out as a joke.” During an entrepreneurial contest, he took note of the numeroushalal carts in Manhattan and quipped to his friends that he was “going to start a chicken and broccoli cart chain” as his business venture.
        p At the same time, he and his family grew up eating the food his grandmother had made from her special recipe (which accounts for that “secret pork sauce”). Even as a kid, Yang wanted to share his grandmother’s food with others and thought about options like opening up a restaurant—particularly in areas with less access to that kind of home-style Taiwanese food, such as Midtown—“but I couldn’t afford it,” he says.
        p Instead, he would take the best of both worlds and combine food carts and Grandma’s special recipe into street vending.
        p “My grandma passed away awhile ago, but I’m sure she’s proud,” Yang says.
        p Yang developed the truck’s business model before graduating from college; and while his family, like any first generation Asian family, at first wondered why he would want to run a food truck after four years of school—both friends and family have since pitched in to help out in areas from operations to cooking.
        p In an amusing story, Yang recounts how Diana saved the truck from rolling around New York City as a giant panda. Initially inspired to model the truck after the huggable Asian icon with black eyes as the windows, he then let Diana take over the design and the truck debuted with its simple classic look of bamboo tree accents (which goes with Cravings’ goal to be green by providing reusable food containers).
        p Although apprehensive in the beginning on how the food would appeal to the general public, Yang has received a gratifyingly positive reaction from the Asian community and also sees the food lines becoming more diverse. “I knew Asian people would love this,” he says, “because my friends would eat this with me. I wasn’t sure with another market.”
        p “I’m getting a lot of support from Taiwanese people,” he also says. “They say it tastes like home-cooking and they can’t have it, around NYC at least. In Flushing, you could probably grab something … but it’s just so far away, for lunchtime especially. I was surprised [by the feedback]. They show a lot of support that we appreciate.”
        p So what’s next for the capable Cravings crew? They’re possibly looking to expand to hours after lunchtime—as in, dinner. And they’ve already gotten requests to road trip to other areas, including the West Coast. But Yang isn’t looking to transition into a flashy franchise with big-budget promotions. “I want people to tell other people about it,” he says, “But I still want it to be a little secret.”
        p So tour guides, put that marker down and show some restraint. Home-cooking is meant to be enjoyed among family and friends.
        p D. Lin works in NYC in publishing.
        p Note: The writer of this article visited the truck early with a friend last week (“early,” meaning before noon) to avoid the lunch rush. Well, there was already a line of twenty-some-odd people.
        p The line moved at a steady pace, however, and no one died of starvation on the sidewalk. Moral of the story: Get there early! Or track them on Twitter and seize your opportunities.
        p Regarding the tastiness of the food, the writer also visited the truck multiple times to eat and take photos of the food; but every time the food arrived, everything looked so good that all food was eaten without any photos taken. This explains the lack of original food photos, and the appropriate publications are thanked for their excellent photos. The writer is, anyway, quite terrible at photographing food but excels at eating it, so perhaps this is all for the best.
        p
          ' -
          a href='http://taiwaneseamerican.org' http://taiwaneseamerican.org

app/views/layouts/_carousel.html.slim
.carousel-container
  <div id="carousel" class="carousel slide">
    <!-- Indicators -->
    <ol class="carousel-indicators">
      <li data-target="#carousel" data-slide-to="0" class="active"></li>
      <li data-target="#carousel" data-slide-to="1"></li>
      / <li data-target="#carousel" data-slide-to="2"></li>
    </ol>

    <!-- Wrapper for slides -->
    <div class="carousel-inner">
      <div class="item active">
        = image_tag "hi-res-truck.jpg", alt: "Bian Dang"
        <div class="carousel-caption">
          <h2>Meet Bian Dang!</h2>
        </div>
      </div>
      <div class="item">
        = image_tag "thomas-truck.jpg", alt: "Thomas from Bian Dang"
        <div class="carousel-caption">
          <h2>Meet Thomas!</h2>
        </div>
      </div>
      / <div class="item">
      /   = image_tag "diana-truck.jpg", alt: "Diana from Bian Dang"
      /   <div class="carousel-caption">
      /     <h2>Meet Diana!</h2>
      /   </div>
      / </div>
    </div>

    <!-- Controls -->
    <a class="left carousel-control" href="#carousel" data-slide="prev">
      <span class="icon-prev"></span>
    </a>
    <a class="right carousel-control" href="#carousel" data-slide="next">
      <span class="icon-next"></span>
    </a>
  </div>

app/views/layouts/_messages.html.slim
- flash.each do |name, msg|
  - if msg.is_a?(String)
    div class=("alert alert-#{name == :notice ? "success" : "error"}") 
      a.close data-dismiss="alert"  ×
      = content_tag :div, msg, :id => "flash_#{name}"

app/views/layouts/_navigation.html.slim
nav.navbar-large
  = nav_link "MENU", root_path
  = nav_link "STORY", story_path
  li
    = image_tag 'bian-dang-logo-flat.png', class: "img-responsive bd-logo", alt: 'Bian Dang NYC'
  = nav_link "CATERING", events_path
  = nav_link "CONTACT", contact_path

nav.navbar-small
  li.nav-li-small
    a href='/'
      = image_tag 'bian-dang-logo-flat.png', class: "img-responsive", alt: 'Bian Dang NYC'
  div.clearfix
  = nav_link_small "MENU", root_path
  = nav_link_small "STORY", story_path
  = nav_link_small "CATERING & EVENTS", events_path
  = nav_link_small "CONTACT", contact_path

app/views/layouts/_twitter.html.slim
.panel.panel-default
  .panel-heading
    h3 Bian Dang's Twitter Feed
  .panel-body
    - bdtw = Twitter.user_timeline("biandangnyc")
    - 0.upto(4) do |i|
      .tweet
        = " #{bdtw[i][:text]}"
        .pull-right
          br
          = " #{bdtw[i][:created_at].strftime("%I:%M%p on %B %d")}"
        .clearfix

app/views/layouts/application.html.slim
doctype html
html
  head
    meta content="width=device-width, initial-scale=1.0" name="viewport"
      title= content_for?(:title) ? yield(:title) : "Bian Dang - New York City's Gourmet Taiwanese Food Truck"
      meta content=(content_for?(:description) ? yield(:description) : "Bian Dang") name="description"
        = stylesheet_link_tag "application", :media => "all"
        = javascript_include_tag "application"
        = csrf_meta_tags
  body
    header
      = render 'layouts/navigation'
      .clearfix
    main role="main"
      = render 'layouts/carousel'
      = render 'layouts/messages'
      .container
        = yield
      .row.footer
        .col-md-3.col-md-offset-1.bottom
          h1 Tweets
          - bdtw = Twitter.user_timeline("biandangnyc")
          - 0.upto(2) do |i|
            .tweet
              = " #{bdtw[i][:text]}"
              .pull-right
                br
                = " #{bdtw[i][:created_at].strftime("%I:%M%p on %B %d")}"
              .clearfix
        .col-md-4.bottom
          h1 Location
          .location 53rd Street between Park and Lexington Avenue
          .location New York, NY 10022
          .location Monday to Friday, 11:30am to 2:30pm
          .location Weekends and Holidays, please check our <a href='http://twitter.com/biandangnyc'>Twitter</a> feed
          .location +1 (212) 695-5995
        .col-md-3.bottom
          h1 Eat. Like? Follow!
          a href='http://twitter.com/biandangnyc' onClick="ga('send', 'Social Media', 'Follow', 'Twitter');"
            .twitter-roll
          a href='http://facebook.com/biandang' onClick="ga('send', 'Social Media', 'Follow', 'Facebook');"
            .facebook-roll
      .footer
        .col-md-10.col-md-offset-1.footer
          span &copy; 2013
          a href='http://www.luckmgmt.com'   Luck Management Corp.
          span.pull-right
            a href="#" Back to top


javascript:
  var _gaq = _gaq || [];
  _gaq.push(['_setAccount', 'UA-35441338-1']);
  _gaq.push(['_trackPageview']);

  (function() {
    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
    ga.src = ('https:' == document.location.protocol ? 'https://' : 'http://') + 'stats.g.doubleclick.net/dc.js';
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
  })();

<link href='http://fonts.googleapis.com/css?family=Roboto:400' rel='stylesheet' type='text/css'>

javascript:
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-49708213-1', 'biandangnyc.com');
  ga('send', 'pageview');

app/views/pages/about.html.slim
- content_for :title do
  | About

app/views/twilio/call.html.slim
= @response.text